PATCH http://localhost:8080/user/changePassword
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI2MzZmNzMwZWMxMTNhYzc5MTQyZjlmOTEiLCJ0b2tlblR5cGUiOiJVU0VSIiwiaWF0IjoxNjY4MjU4MjQyLCJleHAiOjE2Njg4NjMwNDJ9.s2AMFj0CLyblSfrxmT8Kux4CW1e4iEdDBKrgVIBWzpk

{
    "name" : "Adnan",
    "oldPassword": "123456",
    "newPassword": "123456"
}