PATCH http://localhost:8080/gardener/changePassword
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYXJkZW5lcklkIjoiNjMyYTBiNTdmNWM5M2IyNGI4MzVmZTg1IiwidG9rZW5UeXBlIjoiR0FSREVORVIiLCJpYXQiOjE2Njg2MTY4MzUsImV4cCI6MTY2OTIyMTYzNX0.ha0ZM0d8DkZjykceLyIqUMriu_J4mmJXTJx8cyCOgZs

{
    "name" : "Benny Smith",
    "oldPassword": "Madnan786*",
    "newPassword": "Madnan786*"
}