GET http://localhost:8080/gardener/all-gardeners
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJnYXJkZW5lcklkIjoiNjMyYTBiNTdmNWM5M2IyNGI4MzVmZTg1IiwidG9rZW5UeXBlIjoiR0FSREVORVIiLCJpYXQiOjE2NjgyNTAwMDEsImV4cCI6MTY2ODg1NDgwMX0.v_RgB86DNuPkh4G5V_c-7SWX2AZFe3bx-jjX_V4Ps9s
