DELETE http://localhost:8080/products/delete/6327043cc3037a7279ffce89
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhZG1pbklkIjoiNjMyNTk5YWRlZGE0OGZkMjE0ZmExNmExIiwidG9rZW5UeXBlIjoiQURNSU4iLCJpYXQiOjE2Njc1MDM0NjEsImV4cCI6MTY2ODEwODI2MX0.m-L0qHzxGpoCr2Lcu4giafUlxApzbPAAEmRWhPdoVgQ
